import { MigrationInterface, QueryRunner } from "typeorm";

export class migrations1670717225166 implements MigrationInterface {
    name = 'migrations1670717225166'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FKUserToken"`);
        await queryRunner.query(`ALTER TABLE "route" DROP CONSTRAINT "FKUserToken"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FKRoute"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FKUser"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP CONSTRAINT "FKUserToken"`);
        await queryRunner.query(`CREATE TABLE "travel" ("id" SERIAL NOT NULL, "description" character varying NOT NULL, "user_id" character varying NOT NULL, "vehicle_id" character varying NOT NULL, "route_id" character varying NOT NULL, "travels" integer NOT NULL, "inactive" boolean NOT NULL DEFAULT false, "date" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_657b63ec7adcf2ecf757a490a67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isAdmin" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "birth_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "PK_187fa17ba39d367e5604b3d1ec9"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "PK_187fa17ba39d367e5604b3d1ec9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "km_per_lt"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "km_per_lt" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ALTER COLUMN "inactive" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "route" DROP CONSTRAINT "PK_08affcd076e46415e5821acf52d"`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" ADD CONSTRAINT "PK_08affcd076e46415e5821acf52d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "distance"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "distance" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "price" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" ALTER COLUMN "inactive" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "PK_edd925b450e13ea36197c9590fc"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "PK_edd925b450e13ea36197c9590fc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "route_id"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "route_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "value" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" ALTER COLUMN "inactive" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP CONSTRAINT "PK_9f236389174a6ccbd746f53dca8"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD CONSTRAINT "PK_9f236389174a6ccbd746f53dca8" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_362d4cb9148e53e7bbc2f660838" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel" ADD CONSTRAINT "FK_fbcfe870df3fa743e7fce6367ed" FOREIGN KEY ("route_id") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel" ADD CONSTRAINT "FK_6f7852d8c7d2efd9ce279a35d5c" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel" ADD CONSTRAINT "FK_d5aaea5c92c7d04354bdf192efd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route" ADD CONSTRAINT "FK_797177a310ed69b8ede51c81a55" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_31ecbdd8bdf47a93916147fbddc" FOREIGN KEY ("route_id") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_8aed1abe692b31639ccde1b0416" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD CONSTRAINT "FK_32f96022cc5076fe565a5cba20b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP CONSTRAINT "FK_32f96022cc5076fe565a5cba20b"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_8aed1abe692b31639ccde1b0416"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_31ecbdd8bdf47a93916147fbddc"`);
        await queryRunner.query(`ALTER TABLE "route" DROP CONSTRAINT "FK_797177a310ed69b8ede51c81a55"`);
        await queryRunner.query(`ALTER TABLE "travel" DROP CONSTRAINT "FK_d5aaea5c92c7d04354bdf192efd"`);
        await queryRunner.query(`ALTER TABLE "travel" DROP CONSTRAINT "FK_6f7852d8c7d2efd9ce279a35d5c"`);
        await queryRunner.query(`ALTER TABLE "travel" DROP CONSTRAINT "FK_fbcfe870df3fa743e7fce6367ed"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_362d4cb9148e53e7bbc2f660838"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP CONSTRAINT "PK_9f236389174a6ccbd746f53dca8"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD CONSTRAINT "PK_9f236389174a6ccbd746f53dca8" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "expense" ALTER COLUMN "inactive" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "value" real NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "route_id"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "route_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "PK_edd925b450e13ea36197c9590fc"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "expense" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "PK_edd925b450e13ea36197c9590fc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "route" ALTER COLUMN "inactive" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "price" real NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "distance"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "distance" real NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" DROP CONSTRAINT "PK_08affcd076e46415e5821acf52d"`);
        await queryRunner.query(`ALTER TABLE "route" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "route" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "route" ADD CONSTRAINT "PK_08affcd076e46415e5821acf52d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "vehicle" ALTER COLUMN "inactive" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "km_per_lt"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "km_per_lt" real NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "PK_187fa17ba39d367e5604b3d1ec9"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "PK_187fa17ba39d367e5604b3d1ec9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "birth_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "isAdmin" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP TABLE "travel"`);
        await queryRunner.query(`ALTER TABLE "users_tokens" ADD CONSTRAINT "FKUserToken" FOREIGN KEY ("user_id", "user_id", "user_id") REFERENCES "users"("id","id","id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FKUser" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FKRoute" FOREIGN KEY ("route_id") REFERENCES "route"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "route" ADD CONSTRAINT "FKUserToken" FOREIGN KEY ("user_id", "user_id", "user_id") REFERENCES "users"("id","id","id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FKUserToken" FOREIGN KEY ("user_id", "user_id", "user_id") REFERENCES "users"("id","id","id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
